/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class verifier_VerifySignature */

#ifndef _Included_verifier_VerifySignature
#define _Included_verifier_VerifySignature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     verifier_VerifySignature
 * Method:    verify
 * Signature: ([B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_verifier_VerifySignature_verify
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
